# Generated by Django 3.2 on 2023-06-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basefinale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichier',
            name='file',
            field=models.FileField(null=True, upload_to='fichier'),
        ),
    ]
