# Generated by Django 3.2 on 2023-06-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basefinale', '0002_fichier_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='description',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
